version: "3.8"

services:
  #Это конфигурация Docker Compose для запуска сервера Lavalink, библиотеки аудиоплеера для ботов Discord.
  discord-lavalink:
    container_name: discord-lavalink
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: lavalink.env
    image: ghcr.io/lavalink-devs/lavalink:3
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"
    volumes:
      - "./lavalink/plugins:/opt/Lavalink/plugins"

networks:
  external:
    external: true
    name: $NETWORK
